// One-shot build script. Downloads Natural Earth's simplified country outlines,
// extracts Japan, projects it to our viewBox via Mercator, projects each city's
// real lat/lon to the same viewBox, and writes a tiny static TS module.
//
// Run with: node scripts/extract-japan.mjs

import { feature } from "topojson-client";
import { geoMercator, geoPath } from "d3-geo";
import { writeFileSync } from "node:fs";

const SOURCES = [
  // 50m has nice detail without being huge
  "https://cdn.jsdelivr.net/npm/world-atlas@2/countries-50m.json",
  "https://unpkg.com/world-atlas@2/countries-50m.json",
];

async function fetchJson() {
  for (const url of SOURCES) {
    try {
      const r = await fetch(url);
      if (r.ok) return r.json();
    } catch {
      /* try next */
    }
  }
  throw new Error("Could not fetch world atlas data from any source.");
}

const W = 1200;
const H = 680;
const PAD = 22;

const world = await fetchJson();
const countries = feature(world, world.objects.countries);
const japan = countries.features.find(
  (f) => f.properties.name === "Japan"
);
if (!japan) {
  console.error("Japan not found in dataset.");
  process.exit(1);
}

// Filter out Okinawa + far-southern islands so the projection zooms on the
// four main islands (Hokkaido, Honshu, Shikoku, Kyushu).
function filterMainIslands(f) {
  if (f.geometry.type === "MultiPolygon") {
    f.geometry.coordinates = f.geometry.coordinates.filter((poly) =>
      poly[0].some(([, lat]) => lat > 30.5)
    );
  }
  return f;
}
const japanMain = filterMainIslands(JSON.parse(JSON.stringify(japan)));

// Mercator projection fit to our viewBox with tight padding
const projection = geoMercator().fitExtent(
  [
    [PAD, PAD],
    [W - PAD, H - PAD],
  ],
  japanMain
);
const path = geoPath(projection);
const dStr = path(japanMain);

// Real city lat/lons (lon, lat order — d3 wants longitude first)
const cities = {
  tokyo:    [139.6503, 35.6762],
  kyoto:    [135.7681, 35.0116],
  osaka:    [135.5023, 34.6937],
  hokkaido: [141.3545, 43.0618], // Sapporo
  kanazawa: [136.6562, 36.5613],
};

// Mt. Fuji and a few other landmarks for decoration
const landmarks = {
  fuji: [138.7274, 35.3606],
};

const proj = (ll) => {
  const p = projection(ll);
  return p ? { x: Math.round(p[0] * 100) / 100, y: Math.round(p[1] * 100) / 100 } : null;
};

const cityCoords = Object.fromEntries(
  Object.entries(cities).map(([k, ll]) => [k, proj(ll)])
);
const landmarkCoords = Object.fromEntries(
  Object.entries(landmarks).map(([k, ll]) => [k, proj(ll)])
);

const out = `// Auto-generated by scripts/extract-japan.mjs — do not edit by hand.
// Source: Natural Earth 1:50m via world-atlas (public domain).

export const JAPAN_PATH = ${JSON.stringify(dStr)};

export const JAPAN_VIEWBOX = "0 0 ${W} ${H}";
export const JAPAN_W = ${W};
export const JAPAN_H = ${H};

export const CITY_COORDS: Record<string, { x: number; y: number }> = ${JSON.stringify(cityCoords, null, 2)};

export const LANDMARKS: Record<string, { x: number; y: number }> = ${JSON.stringify(landmarkCoords, null, 2)};
`;

writeFileSync("lib/japan-data.ts", out);
console.log("✓ Wrote lib/japan-data.ts");
console.log("  cities:", cityCoords);
console.log("  landmarks:", landmarkCoords);
console.log("  path length:", dStr.length, "chars");
